require("alex.remap")
require("alex.quicker")
require("alex.hud")
require("alex.plan_viewer")
require("gh_dashboard").setup()
require("gh_dashboard.reader").setup()
require("gh_dashboard.watchlist").setup()
require("gh_dashboard.user_watchlist").setup()
vim.cmd("set number")
vim.cmd("set foldmethod=indent")
vim.opt.laststatus = 3
