require("alex.packer")
require("alex.remap")
require("alex.quicker")
require("alex.hud")
require("alex.plan_viewer")
require("alex.github_dashboard").setup()
require("alex.gh_reader").setup()
require("alex.gh_watchlist").setup()
vim.cmd("set number")
vim.cmd("set foldmethod=indent")
vim.opt.laststatus = 3
